### ISSUE TITLE
Any logs to check what I am doing wrong?

### ISSUE THREAD

**Issue by mannp** [MichelePalmieri/grav-piwik-plugin#8]
I have added the following to Piwik URL and id of 3 in ID and nothing...

//subdomain.domain.co.uk/piwik/ or subdomain.domain.co.uk/piwik/ or //subdomain.domain.co.uk/piwik or subdomain.domain.co.uk/piwik 

I have two other mains tracking with no issues.

Piwik v3.2

Nothing is getting logged though.

**Comment by geschke** [comment]
Please provide more information. How about the generated JavaScript/HTML source? Do you find anything in the browser's debugger? Do you find requests to the Piwik server? Does the problem exists with every browser? And so on... 

Kind regards,
   Ralf

**Comment by mannp** [comment]
generated source? you mean which grav template I am using?

Browsers debugger -> Failed to load resource: subdomain.domain.co.uk/piwik//piwik.js the server responded with a status of 502 ()

Note the // after piwik, should the url have no slash at the end then....

No data appears in piwik.

Safari, Firefox and Chrome have the same result of no data being logged back to piwik.

Thanks in advance :)

**Comment by geschke** [comment]
No, I mean the source code of your page. Grav generates HTML and JavaScript (most browsers: right mouse key -> show sourcecode (or similar)). 

But: your Piwik installations throws a 502 error? Then it's a problem with Piwik, not Grav!

**Comment by mannp** [comment]
As I said 2 other sites are working fine.

Ok, so I can see the source and note there shouldn't be a slash at the end of the url in the config, so have removed mine.

Will check tomorrow now I can see the code.

Only just started with grav and couldn't see past the obvious of it creating source code.

Thanks

**Comment by geschke** [comment]
Maybe it's a problem with Piwik configuration? 
What happens if you try to request the url subdomain.domain.co.uk/piwik//piwik.js from your browser? I can't imagine that the debugger says 502 and the same URL does work correctly when requesting in the browser. That seems a bit irrationally. Please try to get the differences between the 2 sites which are working fine and the non-working site. 
 
Sorry, but I'm unable to help with so few information. It's a kind of "my car does not drive - why?". I don't know your site structure, your network, your installation and so on. I could have a look at your page, but not with the example "subdomain.doman.tld" URLs. Did you enter the site ID? Which version of Grav, PHP and so on do you run?

**Comment by mannp** [comment]
The piwik.js works fine when entered in the browser manually so I do not believe its the instance. It maybe the internal grav test site trying to access my external domain via my proxy.

What information that you asked for have I not given already? The ID is already in the first line of the first post, but anyway, thanks, I will try and make some further progress myself.

**Comment by geschke** [comment]
Is there any update on this issue? Does it work?

**Comment by mannp** [comment]
Moved to jekyll, will close, thanks.
